# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 29b432e827e818b0d9dede40c4211bbd853f7b1ed7918a8536695f57a5aacc307cd045b750d3e898fa83ff70f1da53e9926b23ca7f1005067dd4ba4b9a74e6c6

test:
  secret_key_base: 483aa76d5df91805f46636b3faa089a7e3d973be10dcb8330b78a6c8a3a36cef833655ca2b7c72138a918306b58663deaf1ee4748736721ec6a0d43f35550675

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
